self.addEventListener('install',e=>{
  console.log("sdfghjkl");
})
self.addEventListener('activate',e=>{
  console.log("actdflzksjfivated");
})
self.addEventListener('fetch',e=>{
  console.log("dsk");
})